config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # resources :carts
  # resources :cart_items

  mount RailsAdmin::Engine => '/admin1', as: 'rails_admin'

  devise_for :users 
  root 'static_pages#home'
  get 'static_pages/about_us', as: :about_us
  get 'static_pages/carriers', as: :carriers
  get 'static_pages/terms', as: :terms
  get 'static_pages/policy', as: :policy
  resources :foods do
    member do
      get :category
    end
  end
  get 'users/:id' => 'users#show' , as: "users_show"
  #delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete
  namespace :admin do
    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :inventory do
      resources :overviews
      resources :adjustments
    end
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources :addresses do
      member do 
        put :select_address
      end
    end
    resources :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :billing_addresses do
      member do
        put :select_address
      end
    end
     resources  :cart_items do
      member do
        put :move_to
      end
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  #include AASM

  has_many :order_items, :inverse_of => :order, :dependent => :destroy

  has_many   :invoices
  has_many   :completed_invoices,   -> { where(state: ['authorized', 'paid']) },  class_name: 'Invoice'
  has_many   :authorized_invoices,  -> { where(state: 'authorized') },      class_name: 'Invoice'
  has_many   :paid_invoices      ,  -> { where(state: 'paid') },            class_name: 'Invoice'
  has_many   :canceled_invoices   , ->  { where(state: 'canceled') }  ,     class_name: 'Invoice'
 
  
  belongs_to   :user
  belongs_to   :ship_address, class_name: 'Address'
  belongs_to   :bill_address, class_name: 'Address'
  accepts_nested_attributes_for :bill_address, :allow_destroy => true
  accepts_nested_attributes_for :ship_address, :allow_destroy => true
  accepts_nested_attributes_for :order_items
  
  before_validation :set_email, :set_number
  after_create      :save_order_number
  #before_save       :update_tax_rates

  attr_accessor :total, :sub_total #, :taxed_total
  
  validates :user_id,     presence: true
  validates :email,       presence: true,
                          format:   { with: CustomValidators::Emails.email_validator } 
  CHARACTERS_SEED = 20
  NUMBER_SEED     = 2002002002000

  # aasm column: :state do
  #   state :in_progress, initial: true
  #   state :complete
  #   state :paid 
  #   state :canceled  


  #   event :complete do
  #     transitions to: :complete, from: :in_progress
  #   end

  #   event :pay, after: :mark_items_paid do
  #     transitions to: :paid, from: [:in_progress, :complete]
  #   end  

  # end

  def mark_items_paid
    order_items.map(&:pay!)
  end



  def first_invoice_amount
    return '' if completed_invoices.empty? && canceled_invoices.empty?
    completed_invoices.last ? completed_invoices.last.amount : canceled_invoices.last.amount
  end

  def status
    return 'not processed' if invoices.empty?
    invoices.last.state
  end

  def self.between(start_time, end_time)
    where("orders.completed_at >= ? AND orders.completed_at <= ?", start_time, end_time)
  end

  def self.order_by_completion
    order('orders.completed_at asc')
  end

  def self.finished
    where({:orders => { :state => ['complete', 'paid']}})
  end

  def self.find_myaccount_details
    includes([:completed_invoices, :invoices])
  end

  def add_cart_item( item, state_id = nil)
    self.save! if self.new_record?
    item.quantity.times do
      oi =  OrderItem.create(
          :order        => self,
          :variant_id   => item.variant.id,
          :price        => item.variant.price)
      self.order_items.push(oi)
    end
  end

  def create_invoice(args,credited_amount)
    invoice_statement = Invoice.new(order_id: self.id, amount: credited_amount, invoice_type: 'PURCHASE')
    invoice_statement.save
    invoices.push(invoice_statement)
    if invoice_statement
      self.order_complete!
      #Notifier.order_confirmation(self.id,invoice_statement.id).deliver_now
    end
  end

  def order_complete!
    self.state = 'complete'
    self.completed_at = Time.zone.now
    update_inventory
  end

  def find_total(force = false)
    self.find_sub_total
    self.total  = self.sub_total
  end

  def find_sub_total
    self.total = 0.0
    order_items.each do |item|
      self.total = self.total + item.price if !item.price.nil?
    end
    self.sub_total = self.total
  end

  def amount_to_credit
    [find_total].min.to_f
  end
  def add_items(variant, quantity, state_id = nil)
    self.save! if self.new_record?
    quantity.times do
      self.order_items.push(OrderItem.create(:order => self,:variant_id => variant.id, :price => variant.price))
    end
  end

  def remove_items(variant, final_quantity)
    current_qty = 0
    items_to_remove = []
    self.order_items.each_with_index do |order_item, i|
      if order_item.variant_id == variant.id
        current_qty = current_qty + 1
        items_to_remove << order_item.id  if (current_qty - final_quantity) > 0
      end
    end
    OrderItem.where(id: items_to_remove).map(&:destroy) unless items_to_remove.empty?
    self.order_items.reload
  end
  
  def self.id_from_number(num)
    num.to_i(CHARACTERS_SEED) - NUMBER_SEED
  end

  def self.find_by_number(num)
    find(id_from_number(num))
  end

  def update_inventory
    #raise "hello"
    self.order_items.each { |item| item.variant.substract_count_on_hand(1) }
  end

  def variant_ids
    order_items.collect{|oi| oi.variant_id }
  end


  def self.include_checkout_objects
    includes([{ship_address: :state},
              {bill_address: :state}])
  end

private
  def item_prices
    order_items.collect{|item| item.adjusted_price }
  end

  def set_email
    self.email = user.email if user_id
  end

  def set_number
    return set_order_number if self.id
    self.number = (Time.now.to_i).to_s(CHARACTERS_SEED)## fake number for friendly_id validator
  end

  def set_order_number
    self.number = (NUMBER_SEED + id).to_s(CHARACTERS_SEED)
  end


  def save_order_number
    set_order_number
    save
  end

end

app/controllers/admin/history/orders_controller.rb
class Admin::History::OrdersController < Admin::BaseController
		def index
			@orders = Order.all
		end

		# GET /admin/history/orders/1
		def show
			#raise "hello"
			@order = Order.includes([:ship_address,{:order_items => [
			    {:variant => [:food]}]
			}]).find(params[:id])
		end
end

app/controllers/myaccount/orders_controller.rb
class Myaccount::OrdersController < Myaccount::BaseController
  # GET /myaccount/orders
  # GET /myaccount/orders.xml
  def index
    @orders = current_user.orders
  end

  # GET /myaccount/orders/1
  # GET /myaccount/orders/1.xml
  # def show
  #   @order = current_user.finished_orders.includes([:invoices]).find_by_number(params[:id])
  # end
  private

  def selected_myaccount_tab(tab)
    tab == 'orders'
  end
end

app/controllers/shopping/orders_controller.rb
class Shopping::OrdersController < Shopping::BaseController
  before_filter :authenticate_user!

  def index
    @order = find_or_create_order
    if f = next_form(@order)
      redirect_to f
    else
      expire_all_browser_cache
    end
  end

  def checkout
    order = find_or_create_order
    @order = session_cart.add_items_to_checkout(order)
    redirect_to next_form_url(order)
  end

  def update
    @order = find_or_create_order
    @order.ip_address = request.remote_ip

    address = @order.bill_address.cc_params

    if  @order.create_invoice({ email: @order.email, billing_address: address, ip: @order.ip_address},
                  @order.amount_to_credit)

      expire_all_browser_cache
      session_cart.mark_items_purchased(@order)
      session[:last_order] = @order.number
      redirect_to( confirmation_shopping_order_url(@order) ) and return
    else
      flash[:notice] = "Sorry dear we are unable to process your order"
      render :action => 'index'
    end
  end

  def confirmation
    if session[:last_order].present? && session[:last_order] == params[:id]
      session[:last_order] = nil
      @order = Order.where(number: params[:id]).includes({order_items: :variant}).first
      render :layout => 'application'
    else
      session[:last_order] = nil
      if current_user.orders.present?
        redirect_to myaccount_overview_url( current_user.orders.last )
      elsif current_user
        redirect_to myaccount_overview_url
      end
    end
  end

end

app/helpers/admin/history/orders_helper.rb
module Admin::History::OrdersHelper
end

app/helpers/myaccount/orders_helper.rb
module Myaccount::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shopping/orders_helper.rb
module Shopping::OrdersHelper
end

app/views/admin/history/orders/index.html.erb
<div class="container">
	

<h3>Orders</h3>

<div class="table">
  <table class="table table-condensed">
    <thead>
      <tr class='odd'>
        <th class='column1_header'>Number</th>
        <th>Email</th>
        <th>Completed at</th>
        <th>Shipped</th>
      </tr>
    </thead>

  <% @orders.each do |order| %>
    <tr class='<%= cycle("odd", "")%>'>
      <td><%= link_to order.number, admin_history_order_path(order) %></td>
      <td><%= order.email %></td>
      <td><%= order.completed_at %></td>
      <td>yes</td>
    </tr>
  <% end %>
  </table>
</div>
</div>

app/views/admin/history/orders/show.html.erb
<div class="container">
<div>
  <b>Order Information:</b>
  <div  id='order-items'
        class='panel '>
      <ul>
            <li><label>Order Number:</label> <%= @order.number %></li>
            <li><label>Customer:    </label> <%#= @order.name %></li>
            <li><label>Email:       </label> <%= @order.email %></li>
            <li><label>Completed at:</label> <%= @order.completed_at%></li>
            <li><label>Shipped:     </label> Yes</li>
      </ul>
  </div>
</div>

<% if @order.order_items.size > 0 %>

  <div>
  <b>Items</b>
    <div  id='order-items'
          class=' panel '>

            <% @order.order_items.each do |item| %>
              <%= item.variant.food.name %> <%= number_to_currency item.total %><br/>
            <% end %>
    </div>
  </div>

<% end %>
<div>
  <b>Shipping Address</b>
  <div  id='order-address'
        class='panel '>
            <%= render :partial => '/shared/compact_address', :locals => {:shopping_address => @order.ship_address} %>
            <br>
            <p><%= link_to 'Change Address', admin_history_order_addresses_path(@order), :class => 'button green' %> <br>
            (This will not change the shipments that have already been placed)</p>
  </div>
</div>
<div>
  <b>Invoices:</b>
  <% @order.invoices.each do |invoice| %>

      <div  id='order-invoices'
            class=' panel'>
          <ul class='vertical-list'>
            <li><label>Number:</label> <%= invoice.number %> </li>
            <li><label>State: </label><%= invoice.state %></li>
            <li><label>at:</label> <%= I18n.localize(invoice.updated_at, :format => :us_time)%></li>
            <li><label>Amount:</label> <%= number_to_currency invoice.amount %></li>
          </ul>
      </div>
  <% end %>
</div>
</div>