config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # resources :carts
  # resources :cart_items

  mount RailsAdmin::Engine => '/admin1', as: 'rails_admin'

  devise_for :users 
  root 'static_pages#home'
  get 'static_pages/about_us', as: :about_us
  get 'static_pages/carriers', as: :carriers
  get 'static_pages/terms', as: :terms
  get 'static_pages/policy', as: :policy
  resources :foods do
    member do
      get :category
    end
  end
  get 'users/:id' => 'users#show' , as: "users_show"
  #delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete
  namespace :admin do
    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :inventory do
      resources :overviews
      resources :adjustments
    end
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources :addresses do
      member do 
        put :select_address
      end
    end
    resources :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :billing_addresses do
      member do
        put :select_address
      end
    end
     resources  :cart_items do
      member do
        put :move_to
      end
    end
  end

end

app/views/shared/_address.html.erb
<p>
  <%= f.label :first_name, 'Address 1' %><br />
  <%= f.text_field :first_name %>
</p>
 
<p>
  <%= f.label :last_name, 'Address 2' %><br />
  <%= f.text_field :last_name %>
</p>
 

app/views/shared/_compact_address.html.erb
  <p><%= shopping_address.name %><br/>
  <% shopping_address.address_lines_array.each do |line| %>
    <%= line %><br/>
  <% end %>
  <%= shopping_address.city_state_zip %><br/>
  </p>

app/views/shared/_footer.html.erb
			<!-- Footer Start -->

			<div class="footer padd">
				<div class="container">
					<div class="row">
						<div class="col-md-3 col-sm-6">
							<!-- Footer widget -->
							<div class="footer-widget">
								<!-- Logo area -->
							<%= link_to root_path do %>
								<!-- Logo area -->
								<div class="logo">
									<%= image_tag 'logo1.jpg', :class => "img-responsive",:alt => ""%>
									<!-- Heading -->
									<h1>Demo Rails</h1>
									<!-- Paragraph -->
	Y								<p>Ithe Sagal Bhetel na Bhau!</p>
								</div>
							<% end  %>
								<!-- Paragraph -->
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.</p>
<!-- 								<hr /> -->
								<!-- Heading -->
							</div> <!--/ Footer widget end -->
						</div>
						<div class="col-md-3 col-sm-6">
							<div class="footer-widget">
								<!-- Heading -->
								<h4>Downloads</h4>
								<div class="contact-details">
									<!-- Address / Icon -->
									<%= image_tag 'androidLink.png',class: 'img-responsive'%>
									<div class="clearfix"></div>
									<br/>
									<%= image_tag 'appStoreLink.png',class: 'img-responsive'%>
									<div class="clearfix"></div>
								</div>
							</div> <!--/ Footer widget end -->
						</div>
						<div class="clearfix visible-sm"></div>
						<div class="col-md-3 col-sm-6">
							<div class="footer-widget">
								<div class="contact-details">
								<h4>Who We Are ?</h4>
								<i class="fa fa-info br-red" aria-hidden="true"></i><span><%= link_to "About Us",about_us_path%></span>
								<div class="clearfix"></div>
								<i class="fa fa-at br-red"></i><span><%= link_to "Carriers",carriers_path%></span>
								<div class="clearfix"></div>
								<i class="fa fa-check br-red"></i><span><%= link_to "Terms & Conditions",terms_path%></span>
								<div class="clearfix"></div>
								<i class="fa fa-file br-red"></i><span><%= link_to "Private Policy & Disclaimer",policy_path%></span>
								<div class="clearfix"></div>
								</div>
							</div> <!--/ Footer widget end -->
						</div>
						<div class="col-md-3 col-sm-6">
							<!-- Footer widget -->
							<div class="footer-widget">
								<!-- Heading -->
								<h4>Contact Us</h4>
								<div class="contact-details">
									<!-- Address / Icon -->
									<i class="fa fa-map-marker br-red"></i> <span>#768, 5th floor, N S Building,<br />Csm Block, Park Road,<br /> Bangalore - 234567</span>
									<div class="clearfix"></div>
									<!-- Contact Number / Icon -->
									<i class="fa fa-phone br-green"></i> <span>+91 88-88-888888</span>
									<div class="clearfix"></div>
									<!-- Email / Icon -->
									<i class="fa fa-envelope-o br-lblue"></i> <span><a href="#">abc@example.com</a></span>
									<div class="clearfix"></div>
								</div>
								<!-- Social media icon -->
								<div class="social">
									<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
									<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
									<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
									<a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
								</div>
							</div> <!--/ Footer widget end -->
						</div>
					</div>
					<!-- Copyright -->
					<div class="footer-copyright">
						<!-- Paragraph -->
						<p>&copy; Copyright 2016 <a href="#">Demo Rails</a></p>
					</div>
				</div>
			</div>

			<!-- Footer End -->

app/views/shared/_header.html.erb
<!-- Header Start -->
			<div class="header">
				<div class="container">
					<!-- Header top area content -->
					<div class="header-top">
						<div class="row">
							<div class="col-md-4 col-sm-4">
								<!-- Header top left content contact -->
								<div class="header-contact">
									<!-- Contact number -->
									<span><i class="fa fa-phone red"></i> 879-938-57791</span>
								</div>
							</div>
							<div class="col-md-4 col-sm-4">
								<!-- Header top right content search box -->
								<div class=" header-search">
									<form class="form" role="form">
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="Search...">
										  <span class="input-group-btn">
											<button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
										  </span>
										</div>
									</form>
								</div>
							</div>
							<div class="col-md-4 col-sm-4">
								<!-- Button Kart -->
								<div class="btn-cart-md">
										<!-- Image -->
									<%= link_to(shopping_cart_items_path, class: "cart-link") do %>
										<%= image_tag 'cart.png', :class => "img-responsive",:alt => ""%>
										<!-- Heading -->
										<h4>Shopping Cart</h4>
										<span class="cart-count"><%= session_cart.shopping_cart_items.length%> Items</span>
										<div class="clearfix"></div>
									<%end%>
									<div class="clearfix"></div>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 col-sm-5">
							<!-- Link -->
							<a href="index.html">
							<%= link_to root_path do %>
								<!-- Logo area -->
								<div class="logo">
									<%= image_tag 'logo1.jpg', :class => "img-responsive",:alt => ""%>
									<!-- Heading -->
									<h1>Demo Rails</h1>
									<!-- Paragraph -->
									<p>Ithe Sagal Bhetel na Bhau!</p>
								</div>
							<% end  %>
							</a>
						</div>
						<div class="col-md-8 col-sm-7">
							<!-- Navigation -->
							<nav class="navbar navbar-default navbar-right" role="navigation">
								<div class="container-fluid">
									<!-- Brand and toggle get grouped for better mobile display -->
									<div class="navbar-header">
										<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
											<span class="sr-only">Toggle navigation</span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
										</button>
									</div>

									<!-- Collect the nav links, forms, and other content for toggling -->
									<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav">
											<li>
											<%= link_to (image_tag 'nav-menu/nav1.jpg', :class => "img-responsive img-rounded",:alt => "")+"Home",root_path%>
											</li>

											<li class="dropdown hidden-xs">
												<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag 'nav-menu/nav2.jpg', :class => "img-responsive img-rounded",:alt => ""%> Menu <b class="caret"></b></a>

												<ul class="dropdown-menu dropdown-md">
													<li>
														<div class="row">
															<% category_header.each do |category|%>
																<% if category.foods.first%>
																	<div class="col-md-4 col-sm-6">
																		<!-- Menu Item -->
																		<div class="menu-item">
																			<!-- Heading -->
																			<h3><%= category.title%></h3>
																			<!-- Image -->
																			<%= image_tag category.category_image.url, :class => "img-responsive",:alt => ""%>
																			<!-- Paragraph -->
																			<p><%= raw category.description.truncate(150)%></p>
																			<!-- Button -->
																			<%= link_to "View Menu",category_food_path(category),class: 'btn btn-danger btn-xs'%>
																		</div>
																	</div>
																<%end%>
															<%end%>
														</div>
													</li>
												</ul>
											</li>
											<li class="dropdown visible-xs">
												<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu <b class="caret"></b></a>
												<ul class="dropdown-menu">
													<li><a href="menu.html">Vegetarian</a></li>
													<li><a href="menu.html">Non Vegetarian</a></li>
													<li><a href="menu.html">Special Menu</a></li>
												</ul>
											</li>
												<%if current_user%>
													<li><%= link_to (image_tag 'nav-menu/signed_user.png' , :class => "img-responsive")+"My Profile" ,  myaccount_overview_path if current_user.present? %></li>
													<li><%= link_to (image_tag 'nav-menu/Logout.png' , :class => "img-responsive")+"SignOut" ,  destroy_user_session_path,method: :delete if current_user.present? %></li>
												<%else%>
													<li><%= link_to (image_tag 'nav-menu/nav3.jpg' , :class => "img-responsive")+"SignIn" ,  new_user_session_path%></li>
												<%end%>
										</ul>
									</div><!-- /.navbar-collapse -->
								</div><!-- /.container-fluid -->
							</nav>
						</div>
					</div>
				</div> <!-- / .container -->
			</div>

			<!-- Header End -->

app/views/shared/_modal.html.erb
<div id="myModal" class="modal fade" data-backdrop="static" data-keyboard="false">
	<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
	<div class="modal-dialog">
		<div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title">Choose Your Area</h4>
      </div>
			<div class="modal-body">
				<div class="row">    
				<%= form_tag(root_path, :method => "get", id: "search-form") do %>
					<div class="col-xs-8 col-xs-offset-2">
						<div class="input-group">
							<div class="input-group-btn search-panel">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							<span id="search_concept">Select City</span> <span class="caret"></span>
							</button>
							<ul class="dropdown-menu" role="menu">
							<li><a href="#Nagpur">Nagpur</a></li>
							<li><a href="#Mumbai">Mumbai</a></li>
							</ul>
							</div>
							<!-- <input type="hidden" name="search_param" value="all" id="search_param">  -->        
							<input type="text" class="form-control" name="x" required placeholder="Search term...">
							<span class="input-group-btn">
							<%= button_tag(type: 'submit', class: "btn btn-large btn-search btn-primary") do %>
							 <i class="fa fa-search"></i> Order Now
							<% end %>
							</span>
						</div>
					</div>
				<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_myaccount_subheader.html.erb
<div class="row">
  <div class="col-md-3 col-sm-3 hidden-xs">
    <!-- inner navigation menu -->
    <div class="navi">
      <!-- heading -->
      <h3>My Menu</h3>
      <!-- list -->
      <ul class="list-unstyled">
        <li><%= link_to '<i class="fa fa-user"></i> My Account'.html_safe, myaccount_overview_path() %></li>
        <li><%= link_to '<i class="fa fa-list-alt"></i>Address'.html_safe, myaccount_addresses_path() %></li>
        <li><%= link_to '<i class="fa fa-edit"></i>Edit Profile'.html_safe, edit_myaccount_overview_path(current_user) %></li>
      </ul>
    </div>
  </div>