config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # resources :carts
  # resources :cart_items

  mount RailsAdmin::Engine => '/admin1', as: 'rails_admin'

  devise_for :users 
  root 'static_pages#home'
  get 'static_pages/about_us', as: :about_us
  get 'static_pages/carriers', as: :carriers
  get 'static_pages/terms', as: :terms
  get 'static_pages/policy', as: :policy
  resources :foods do
    member do
      get :category
    end
  end
  get 'users/:id' => 'users#show' , as: "users_show"
  #delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete
  namespace :admin do
    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :inventory do
      resources :overviews
      resources :adjustments
    end
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources :addresses do
      member do 
        put :select_address
      end
    end
    resources :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :billing_addresses do
      member do
        put :select_address
      end
    end
     resources  :cart_items do
      member do
        put :move_to
      end
    end
  end

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_one :variant

  validate :must_have_stock

  def add_count_on_hand(num)
    if variant.low_stock?
      lock!
      self.count_on_hand = count_on_hand + num.to_i
      save!
    else
      sql = "UPDATE inventories SET count_on_hand = (#{num} + count_on_hand) WHERE id = #{self.id}"
      ActiveRecord::Base.connection.execute(sql)
    end
  end

private
  def must_have_stock
      if (count_on_hand - count_pending_to_customer) < 0
        errors.add :count_on_hand, 'There is not enough stock to sell this item'
      end
  end
end

app/controllers/admin/inventory/adjustments_controller.rb
class Admin::Inventory::AdjustmentsController < Admin::BaseController
	def index
		@foods = Food.all
	end
	def show
		@food = Food.includes(:variants).find(params[:id])
	end

	def edit
		@variant = Variant.includes(:food).find(params[:id])
	end

	def update
		@variant = Variant.find(params[:id])
		if params[:variant][:qty_to_add].present?
			if @variant.update_attributes(allowed_params)
				flash[:notice] = "Inventory updated succesfully"
				redirect_to admin_inventory_adjustment_url(@variant)
			else
				flash[:warning] = "Can not be updated"
				render :action => 'edit', :id => params[:id]
			end
		end
	end

private
	def allowed_params
		params.require(:variant).permit(:qty_to_add)
	end
end

app/controllers/admin/inventory/overviews_controller.rb
class Admin::Inventory::OverviewsController < Admin::BaseController
	def index
		@foods = Food.active.includes({:variants => [:inventory]})
		
	end
end

app/helpers/admin/inventory/adjustments_helper.rb
module Admin::Inventory::AdjustmentsHelper
end

app/helpers/admin/inventory/overviews_helper.rb
module Admin::Inventory::OverviewsHelper
end

app/views/admin/inventory/adjustments/_form.html.erb
<div>
	<%= f.label :qty_to_add %>
</div>

<div>
	<%= f.number_field :qty_to_add, {:step => 1} %>
</div>

app/views/admin/inventory/adjustments/edit.html.erb
<h1> Inventory Adjustment for <%= @variant.product_name%></h1>

<%= form_for(@variant, :url => admin_inventory_adjustment_path(@variant)) do |f| %>
	<%= render :partial => 'form',:locals => {:f => f} %>

	<%= f.submit "Update Inventory"%>
<% end %>


<table>
  <thead>
    <tr>
      <th>SKU</th>
      <th>count on hand</th>
      <th>pending to customer</th>
      <th>count pending from supplier</th>
      <th></th>
    </tr>
  </thead>
    <tr>
      <td><%= @variant.sku %></td>
      <td><%= @variant.inventory.count_on_hand %></td>
      <td><%= @variant.inventory.count_pending_to_customer %></td>
      <td><%= @variant.inventory.count_pending_from_supplier %></td>
    </tr>
</table>


<p>
  <%= link_to "Show #{@variant.product_name}" , admin_inventory_adjustment_path( @variant.food), :class => 'button' %> |
  <%= link_to 'View Products', admin_inventory_adjustments_path, :class => 'button' %>
</p>

app/views/admin/inventory/adjustments/index.html.erb
<h3>Inventory Adjustments</h3>

<div>
  <table>
    <thead>
    <tr class='odd'>
      <th class='column1_header'>Name</th>
    </tr>
    </thead>
    <% for food in @foods %>
      <tr>
        <td><%= link_to food.name, admin_inventory_adjustment_path(food) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/inventory/adjustments/show.html.erb
<h3>Inventory Adjustment for <%= @food.name %></h3>

<div class="admin_adjustments">
  <table>
    <thead>
      <tr>
        <th>SKU</th>&nbsp;
        <th>count on hand</th>
        <th>pending to customer</th>
        <th>count pending from supplier</th>
        <th></th>
      </tr>
    </thead>
    <% @food.variants.each do |variant| %>
      <tr>
        <td><%= variant.sku %></td>
        <td><%= variant.inventory.count_on_hand %></td>
        <td><%= variant.inventory.count_pending_to_customer %></td>
        <td><%= variant.inventory.count_pending_from_supplier %></td>
        <td><%= link_to "Change", edit_admin_inventory_adjustment_path(variant) %></td>
      </tr>
    <% end %>
  </table>
</div>

<p>
  <%= link_to "View Other Product", admin_inventory_adjustments_path, :class => 'button' %>
  <%#= link_to "Back to Product", admin_merchandise_product_path(@food), :class => 'button' %>
</p>