config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # resources :carts
  # resources :cart_items

  mount RailsAdmin::Engine => '/admin1', as: 'rails_admin'

  devise_for :users 
  root 'static_pages#home'
  get 'static_pages/about_us', as: :about_us
  get 'static_pages/carriers', as: :carriers
  get 'static_pages/terms', as: :terms
  get 'static_pages/policy', as: :policy
  resources :foods do
    member do
      get :category
    end
  end
  get 'users/:id' => 'users#show' , as: "users_show"
  #delete "carts/:item_id/", to: "carts#destroy", as: :cart_item_delete
  namespace :admin do
    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :inventory do
      resources :overviews
      resources :adjustments
    end
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources :addresses do
      member do 
        put :select_address
      end
    end
    resources :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :billing_addresses do
      member do
        put :select_address
      end
    end
     resources  :cart_items do
      member do
        put :move_to
      end
    end
  end

end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
  has_many :addresses

  BILLING   = 'Billing'
  SHIPPING  = 'Shipping'
  #ORDER     = 'Order'
  NAMES     = [BILLING, SHIPPING] #, ORDER

  BILLING_ID  = 1
  SHIPPING_ID = 2
  #ORDER_ID    = 3


  validates :name, :presence => true,       :length => { :maximum => 55 }

end

app/controllers/myaccount/addresses_controller.rb
class Myaccount::AddressesController < Myaccount::BaseController
  helper_method :countries

  def index
    @addresses = current_user.shipping_addresses
  end

  def show
    @address = current_user.addresses.find(params[:id])
  end

  def new
    form_info
    @address = Address.new
    if !Settings.require_state_in_address && countries.size == 1
      @address.country = countries.first
    end
    @address.default = true          if current_user.default_shipping_address.nil?
    @form_address = @address
  end

  def create
    @address = current_user.addresses.new(allowed_params)
    @address.default = true          if current_user.default_shipping_address.nil?
    @address.billing_default = true  if current_user.default_billing_address.nil?

    respond_to do |format|
      if @address.save
        format.html { redirect_to(myaccount_address_url(@address), :notice => 'Address was successfully created.') }
      else
        @form_address = @address
        form_info
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    form_info
    @form_address = @address = current_user.addresses.find(params[:id])
  end

  # This is not normal because you should never Update an address.
  #   THE ADDRESS could point to an existing order which needs to keep the same address
  def update
    @address = current_user.addresses.new(allowed_params)
    @address.replace_address_id = params[:id] # This makes the address we are updating inactive if we save successfully

    # if we are editing the current default address then this is the default address
    @address.default         = true if params[:id].to_i == current_user.default_shipping_address.try(:id)
    @address.billing_default = true if params[:id].to_i == current_user.default_billing_address.try(:id)

    respond_to do |format|
      if @address.save
        format.html { redirect_to(myaccount_address_url(@address), :notice => 'Address was successfully updated.') }
      else
        # the form needs to have an id
        @form_address = current_user.addresses.find(params[:id])
        # the form needs to reflect the attributes to customer entered
        @form_address.attributes = allowed_params
        form_info
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @address = current_user.addresses.find(params[:id])
    @address.inactive!
    flash[:warning] = "Successfully destroyed address."
    redirect_to myaccount_addresses_url
  end

  private

  def allowed_params
    params.require(:address).permit(:first_name, :last_name, :address1, :address2, :city, :state_id, :state_name, :zip_code, :default, :billing_default, :country_id)
  end

  def form_info
    @states = State.form_selector
  end

  def selected_myaccount_tab(tab)
    tab == 'address'
  end
  def countries
    @countries ||= Country.active
  end
end

app/controllers/shopping/addresses_controller.rb
class Shopping::AddressesController < Shopping::BaseController
  helper_method :countries
  # GET /shopping/addresses
  def index
    @form_address = @shopping_address = Address.new
    if !Settings.require_state_in_address && countries.size == 1
      @shopping_address.country = countries.first
    end
    form_info
  end

  # GET /shopping/addresses/1/edit
  def edit
    form_info
    @form_address = @shopping_address = Address.find(params[:id])
  end

  # POST /shopping/addresses
  def create
    if params[:address].present?
      @shopping_address = current_user.addresses.new(allowed_params)
      @shopping_address.default = true          if current_user.default_shipping_address.nil?
      @shopping_address.billing_default = true  if current_user.default_billing_address.nil?
      @shopping_address.save
      @form_address = @shopping_address
    elsif params[:shopping_address_id].present?
      @shopping_address = current_user.addresses.find(params[:shopping_address_id])
    end

      if @shopping_address.id
        update_order_address_id(@shopping_address.id)
        redirect_to(shopping_orders_url, :notice => 'Address was successfully created.')
      else
        form_info
        render :action => "index"
      end
  end

  def update
    @shopping_address = current_user.addresses.new(allowed_params)
    @shopping_address.replace_address_id = params[:id] # This makes the address we are updating inactive if we save successfully

    # if we are editing the current default address then this is the default address
    @shopping_address.default         = true if params[:id].to_i == current_user.default_shipping_address.try(:id)
    @shopping_address.billing_default = true if params[:id].to_i == current_user.default_billing_address.try(:id)

      if @shopping_address.save
        update_order_address_id(@shopping_address.id)
        redirect_to(shopping_shipping_methods_url, :notice => 'Address was successfully updated.')
      else
        # the form needs to have an id
        @form_address = current_user.addresses.find(params[:id])
        # the form needs to reflect the attributes to customer entered
        @form_address.attributes = allowed_params
        @states     = State.form_selector
        render :action => "edit"
      end
  end

  def select_address
    address = current_user.addresses.find(params[:id])
    update_order_address_id(address.id)
    redirect_to shopping_orders_url
  end

  def destroy
    @shopping_address = Address.find(params[:id])
    @shopping_address.update_attributes(:active => false)

    redirect_to(shopping_addresses_url)
  end

  private

  def allowed_params
    params.require(:address).permit(:first_name, :last_name, :address1, :address2, :city, :state_id, :state_name, :zip_code, :default, :billing_default, :country_id)
  end

  def form_info
    @shopping_addresses = current_user.shipping_addresses
    @states     = State.form_selector
  end

  def update_order_address_id(id)
    session_order.update_attributes(
                          :ship_address_id => id ,
                          :bill_address_id => (session_order.bill_address_id ? session_order.bill_address_id : id)
                                    )
  end

  def countries
    @countries ||= Country.active
  end

end

app/controllers/shopping/base_controller.rb
class Shopping::BaseController < ApplicationController
  helper_method :session_order, :session_order_id
private

  def next_form_url(order)
    next_form(order) || shopping_orders_url
  end

  def next_form(order)
    # if cart is empty
    if session_cart.shopping_cart_items.empty?
      flash[:warning] = "You don't have anything in cart"
      return foods_url
    ## If we are insecure
    elsif not_secure?
      session[:return_to] = shopping_orders_url
      return new_user_session_path()
    elsif session_order.ship_address_id.nil?
      return shopping_addresses_url()
    end
  end

  def session_order
    find_or_create_order
  end

  def not_secure?
    !current_user
  end

  def find_or_create_order
    return @session_order if @session_order
    if session[:order_id]
      @session_order = current_user.orders.include_checkout_objects.find(session[:order_id])
      create_order if !@session_order
    else
      create_order
    end
    @session_order
  end

  def create_order
    @session_order = current_user.orders.create(:number       => Time.now.to_i,
                                                :ip_address   => request.env['REMOTE_ADDR'],
                                                :bill_address => current_user.billing_address  )
    add_new_cart_items(session_cart.shopping_cart_items)
    session[:order_id] = @session_order.id
  end

  def add_new_cart_items(items)
    items.each do |item|
      @session_order.add_items(item.variant,item.quantity)
    end
  end

end

app/controllers/shopping/billing_address_controller.rb
class Shopping::BillingAddressesController < Shopping::BaseController
  helper_method :countries, :phone_types
  # GET /shopping/addresses
  def index
    if session_cart.shopping_cart_items.empty?
      flash[:notice] = I18n.t('do_not_have_anything_in_your_cart')
      redirect_to foods_url and return
    end
    @form_address = @shopping_address = Address.new
    @form_address.phones.build
    if !Settings.require_state_in_address && countries.size == 1
      @shopping_address.country = countries.first
    end
    form_info
  end

  # GET /shopping/addresses/1/edit
  def edit
    form_info
    @form_address = @shopping_address = Address.find(params[:id])
  end

  # POST /shopping/addresses
  def create
    if params[:address].present?
      @shopping_address = current_user.addresses.new(allowed_params)
      @shopping_address.default = true          if current_user.default_shipping_address.nil?
      @shopping_address.billing_default = true  if current_user.default_billing_address.nil?
      @shopping_address.save
      @form_address = @shopping_address
    elsif params[:shopping_address_id].present?
      @shopping_address = current_user.addresses.find(params[:shopping_address_id])
    end

      if @shopping_address.id
        update_order_address_id(@shopping_address.id)
        redirect_to(next_form_url(session_order))
      else
        form_info
        render :action => "index"
      end
  end

  def update
    @shopping_address = current_user.addresses.new(allowed_params)
    @shopping_address.replace_address_id = params[:id] # This makes the address we are updating inactive if we save successfully

    # if we are editing the current default address then this is the default address
    @shopping_address.default         = true if params[:id].to_i == current_user.default_shipping_address.try(:id)
    @shopping_address.billing_default = true if params[:id].to_i == current_user.default_billing_address.try(:id)

      if @shopping_address.save
        update_order_address_id(@shopping_address.id)
        redirect_to(next_form_url(session_order))
      else
        # the form needs to have an id
        @form_address = current_user.addresses.find(params[:id])
        # the form needs to reflect the attributes to customer entered
        @form_address.attributes = allowed_params
        @form_address.phones.build if @form_address.phones.empty?
        @states     = State.form_selector
        render action: "edit"
      end
  end

  def select_address
    address = current_user.addresses.find(params[:id])
    update_order_address_id(address.id)
    redirect_to next_form_url(session_order)
  end

  def destroy
    @shopping_address = Address.find(params[:id])
    @shopping_address.update_attributes(active: false)

    redirect_to(shopping_billing_addresses_url)
  end

  private

  def selected_checkout_tab(tab)
    tab == 'billing-address'
  end

  def allowed_params
    params.require(:address).permit(:first_name, :last_name, :address1, :address2, :city, :state_id, :state_name, :zip_code, :default, :billing_default, :country_id)
  end

  def phone_types
    @phone_types ||= PhoneType.all.map{|p| [p.name, p.id]}
  end

  def form_info
    @shopping_addresses = current_user.shipping_addresses
    @states     = State.form_selector
  end

  def update_order_address_id(id)
    session_order.update_attributes(
                          :bill_address_id => id
                                    )
  end
end

app/controllers/shopping/cart_items_controller.rb
class Shopping::CartItemsController < Shopping::BaseController

  # GET /shopping/cart_items
  def index
    @cart_items       = session_cart.shopping_cart_items
    @saved_cart_items = session_cart.saved_cart_items
  end

  # POST /shopping/cart_items
  def create
    session_cart.save if session_cart.new_record?
    if params[:cart_item]
      qty = params[:cart_item][:quantity].to_i
      vari = params[:cart_item][:variant_id]
    else
      qty = params[:quantity].to_i
      vari = params[:variant_id]
    end
    
    if cart_item = session_cart.add_variant(vari, most_likely_user, qty)
      session_cart.save_user(most_likely_user)
      #flash[:success] = "Item added succesfully in cart"
        respond_to do |format|
          format.js
        end
    else
      variant = Variant.includes(:food).find_by_id(params[:cart_item][:variant_id])
      if variant
        redirect_to(product_url(variant.product))
      else
        flash[:notice] = "Something went wrong"
        redirect_to root_path
      end
    end
  end

  # PUT /carts/1
  def update
    if session_cart.update_attributes(allowed_params)
      if params[:commit] && params[:commit] == "Checkout"
        redirect_to( checkout_shopping_order_url('Checkout'))
      else
        redirect_to(shopping_cart_items_url(), :notice => I18n.t('item_passed_update') )
      end
    else
      redirect_to(shopping_cart_items_url(), :notice => I18n.t('item_failed_update') )
    end
  end
## TODO
  ## This method moves saved_cart_items to your shopping_cart_items or saved_cart_items
  #   this method is called using AJAX and returns json. with the object moved,
  #   otherwise false is returned if there is an error
  #   method => PUT
  def move_to
    @cart_item = session_cart.cart_items.find(params[:id])
    if @cart_item.update_attributes(:item_type_id => params[:item_type_id])
      redirect_to(shopping_cart_items_url() )
    else
      redirect_to(shopping_cart_items_url(), :notice => I18n.t('item_failed_update') )
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    session_cart.remove_variant(params[:variant_id]) if params[:variant_id]
    respond_to do |format|
      format.js
    end
  end

  private
  def allowed_params
    params.require(:cart).permit!
  end

end

app/controllers/shopping/orders_controller.rb
class Shopping::OrdersController < Shopping::BaseController
  before_filter :authenticate_user!

  def index
    @order = find_or_create_order
    if f = next_form(@order)
      redirect_to f
    else
      expire_all_browser_cache
    end
  end

  def checkout
    order = find_or_create_order
    @order = session_cart.add_items_to_checkout(order)
    redirect_to next_form_url(order)
  end

  def update
    @order = find_or_create_order
    @order.ip_address = request.remote_ip

    address = @order.bill_address.cc_params

    if  @order.create_invoice({ email: @order.email, billing_address: address, ip: @order.ip_address},
                  @order.amount_to_credit)

      expire_all_browser_cache
      session_cart.mark_items_purchased(@order)
      session[:last_order] = @order.number
      redirect_to( confirmation_shopping_order_url(@order) ) and return
    else
      flash[:notice] = "Sorry dear we are unable to process your order"
      render :action => 'index'
    end
  end

  def confirmation
    if session[:last_order].present? && session[:last_order] == params[:id]
      session[:last_order] = nil
      @order = Order.where(number: params[:id]).includes({order_items: :variant}).first
      render :layout => 'application'
    else
      session[:last_order] = nil
      if current_user.orders.present?
        redirect_to myaccount_overview_url( current_user.orders.last )
      elsif current_user
        redirect_to myaccount_overview_url
      end
    end
  end

end

app/helpers/myaccount/addresses_helper.rb
module Myaccount::AddressesHelper
end

app/helpers/shopping/addresses_helper.rb
module Shopping::AddressesHelper
end

app/helpers/shopping/base_helper.rb
module Shopping::BaseHelper
end

app/helpers/shopping/billing_address_helper.rb
module Shopping::BillingAddressHelper
end

app/helpers/shopping/cart_items_helper.rb
module Shopping::CartItemsHelper
end

app/helpers/shopping/orders_helper.rb
module Shopping::OrdersHelper
end

app/views/shopping/addresses/_form.html.erb
<!-- Checkout Start -->
<div class="checkout">
    <% if @shopping_address.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@shopping_address.errors.count, "error") %> prohibited this shipping address from being saved:</h2>

        <ul>
        <% @shopping_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <!-- Heading -->
  <div class="container">
    <h4>Shipping & Billing Details</h4>
    <div class="row">
    <div class="col-md-7 col-sm-6">
    <!-- Checkout Form -->
    <div class="form-group">
    <label for="inputName" class="col-md-2 control-label">FirstName</label>
    <div class="col-md-8">
    <%= f.text_field :first_name,class: 'form-control', placeholder: 'FirstName',:required => true %>
    </div>
    </div>            
    <div class="form-group">
    <label for="inputEmail1" class="col-md-2 control-label">LastName</label>
    <div class="col-md-8">
    <%= f.text_field :last_name,class: 'form-control', placeholder: 'LastName' ,:required => true%>
    </div>
    </div>
    <div class="form-group">
    <label for="inputEmail1" class="col-md-2 control-label">City</label>
    <div class="col-md-8">
    <%= f.text_field :city,class: 'form-control', placeholder: 'City',:required => true %>
    </div>
    </div>
    <div class="form-group">
    <% if Settings.require_state_in_address %>
    <%= f.label    :state_id, "State/Province",class: 'col-md-2 control-label' %>
    <div class="col-md-8">
    <%= f.select   :state_id, @states,
    {:include_blank => true, :prompt => "State"},class: 'form-control' %>
    </div>                
    <% elsif countries.size == 1 %>
    <div class="field column">
    <%= f.label :country_id, "Country",class: 'col-md-2 control-label' %>
    <%= countries.first.name %>
    <%= f.hidden_field   :country_id %>
    </div>
    <% else %>
    <div class="field column">
    <%= f.label    :country_id, "Country", class: 'col-md-2 control-label'  %>
    <%= f.select   :country_id, select_countries,
    :include_blank => true,class: 'form-control' %>
    </div>
    <% end %>
    </div>   
    <div class="form-group">
    <label for="inputAddress" class="col-md-2 control-label">Address1</label>
    <div class="col-md-8">
    <%= f.text_area :address1,class: 'form-control',placeholder: 'Address1',rows: '3',:required => true %>
    </div>
    </div>           
    <div class="form-group">
    <label for="inputAddress" class="col-md-2 control-label">Address2</label>
    <div class="col-md-8">
    <%= f.text_area :address2,class: 'form-control',placeholder: 'Address2' %>
    </div>
    </div>
    <div class="form-group">
    <label for="inputZip" class="col-md-2 control-label">Zip Code</label>
    <div class="col-md-8">
    <!--  <input type="text" class="form-control" id="inputZip" placeholder="Zip Code"> -->
    <%= f.text_field :zip_code ,class: 'form-control',placeholder: 'Zip Code',:required => true%>
    </div>
    </div>
    <div class="form-group">
    <div class="col-md-offset-2 col-md-8">
    <div class="checkbox">
    <label>
    <%= f.check_box :default %> Make this my default shipping address
    </label>
    </div>
    </div>
    </div>
    <div class="form-group">
    <div class="col-md-offset-2 col-md-8">
    <%= f.submit 'Confirm Order', :class => 'btn btn-danger btn-sm' %>&nbsp;
    <button type="reset" class="btn btn-default btn-sm">Reset</button>
    </div>
    </div>
  </div>
</div>
<!-- Checkout End -->

app/views/shopping/addresses/index.html.erb
   <% if  @shopping_addresses.empty? %>
      <%= form_for @shopping_address, url: shopping_addresses_path, html: {class: 'form-horizontal'} do |address_form| %>
        <%= render :partial =>  'form', :locals => {:f => address_form}  %>
      <% end %>
  <% else %>
   <div class="container">
    <h3>Pick a Shipping Address</h3>
  <% end %>

  <% @shopping_addresses.each do |shopping_address| %>
     <div class="col-md-5 col-sm-6">
    <!-- Checkout sidebar items -->
       <div class="sidebar-item">
          <i class="fa fa-truck br-green pull-right"></i>
          <div class="clearfix"></div>
        <%= render :partial => '/shared/compact_address', :locals => {:shopping_address => shopping_address} %>
        <%= button_to 'Use', select_address_shopping_address_path(shopping_address), :class => 'btn btn-primary', :method => :put %><br/>
        
        <%= link_to 'Edit', edit_shopping_address_path(shopping_address) ,class: 'btn btn-primary'%>
        <%= link_to 'Delete', shopping_address_path(shopping_address), :data => {:confirm => 'Are you sure?'}, :method => :delete,class: 'btn btn-danger' %>
      </div>
    </div>
  <% if session_order %>
    <%= link_to 'Order Summary', shopping_orders_path, :class => 'btn btn-primary' %>
  <% end %>
  <%end%>
</div>